// <auto-generated />
using System;
using IsEmriTakip.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsEmriTakip.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029133202_AnaTablolarVeIliskilerEklendi")]
    partial class AnaTablolarVeIliskilerEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsEmriTakip.API.Models.Durum", b =>
                {
                    b.Property<int>("DurumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DurumID"));

                    b.Property<string>("DurumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DurumID");

                    b.ToTable("Durumlar");

                    b.HasData(
                        new
                        {
                            DurumID = 1,
                            DurumAdi = "Atandı"
                        },
                        new
                        {
                            DurumID = 2,
                            DurumAdi = "Devam Ediyor"
                        },
                        new
                        {
                            DurumID = 3,
                            DurumAdi = "Tamamlandı"
                        },
                        new
                        {
                            DurumID = 4,
                            DurumAdi = "İptal Edildi"
                        });
                });

            modelBuilder.Entity("IsEmriTakip.API.Models.IsEmri", b =>
                {
                    b.Property<int>("IsEmriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsEmriID"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AtananTeknisyenID")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("DurumID")
                        .HasColumnType("int");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanYoneticiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OncelikID")
                        .HasColumnType("int");

                    b.HasKey("IsEmriID");

                    b.HasIndex("AtananTeknisyenID");

                    b.HasIndex("DurumID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("OlusturanYoneticiID");

                    b.HasIndex("OncelikID");

                    b.ToTable("IsEmirleri");
                });

            modelBuilder.Entity("IsEmriTakip.API.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriID = 1,
                            KategoriAdi = "Bakım"
                        },
                        new
                        {
                            KategoriID = 2,
                            KategoriAdi = "Arıza"
                        },
                        new
                        {
                            KategoriID = 3,
                            KategoriAdi = "Montaj"
                        });
                });

            modelBuilder.Entity("IsEmriTakip.API.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("IsEmriTakip.API.Models.Oncelik", b =>
                {
                    b.Property<int>("OncelikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OncelikID"));

                    b.Property<string>("OncelikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OncelikID");

                    b.ToTable("Oncelikler");

                    b.HasData(
                        new
                        {
                            OncelikID = 1,
                            OncelikAdi = "Düşük"
                        },
                        new
                        {
                            OncelikID = 2,
                            OncelikAdi = "Orta"
                        },
                        new
                        {
                            OncelikID = 3,
                            OncelikAdi = "Yüksek"
                        });
                });

            modelBuilder.Entity("IsEmriTakip.API.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            RolAdi = "Yonetici"
                        },
                        new
                        {
                            RolID = 2,
                            RolAdi = "Teknisyen"
                        });
                });

            modelBuilder.Entity("IsEmriTakip.API.Models.IsEmri", b =>
                {
                    b.HasOne("IsEmriTakip.API.Models.Kullanici", "AtananTeknisyen")
                        .WithMany()
                        .HasForeignKey("AtananTeknisyenID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IsEmriTakip.API.Models.Durum", "Durum")
                        .WithMany()
                        .HasForeignKey("DurumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsEmriTakip.API.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsEmriTakip.API.Models.Kullanici", "OlusturanYonetici")
                        .WithMany()
                        .HasForeignKey("OlusturanYoneticiID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsEmriTakip.API.Models.Oncelik", "Oncelik")
                        .WithMany()
                        .HasForeignKey("OncelikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtananTeknisyen");

                    b.Navigation("Durum");

                    b.Navigation("Kategori");

                    b.Navigation("OlusturanYonetici");

                    b.Navigation("Oncelik");
                });

            modelBuilder.Entity("IsEmriTakip.API.Models.Kullanici", b =>
                {
                    b.HasOne("IsEmriTakip.API.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
